const IMOVEIS_DATA = [
  {
    "id": "665313",
    "title": "Apartamento no Rita Vieira",
    "type": "Apartamento",
    "location": "Campo Grande - MS",
    "neighborhood": "Rita Vieira",
    "price": "R$ 200.000",
    "features": [
      "Área total: 47,00 m²",
      "Área construída: 47,00 m²",
      "Banheiro: 1",
      "Vaga: 1",
      "Condomínio: R$ 400,00",
      "IPTU: R$ 1.200,00",
      "1 Sala de estar",
      "1 Sala de jantar",
      "1 Sala de TV",
      "1 Wc social",
      "1 Vaga(s) de garagem",
      "Salão de Festas",
      "Calçada",
      "Piscina",
      "Campo de futebol",
      "Piscina infantil",
      "Academia",
      "Área de lazer",
      "Estacionamento para visitas",
      "Portaria",
      "Quiosque",
      "Aceita permuta",
      "Imóvel alugado com renda",
      "Esgoto",
      "Rede elétrica",
      "Área de serviço",
      "Play-ground",
      "Churrasqueira",
      "Jardim",
      "Interfone",
      "Porteiro eletrônico",
      "Quarto empregada",
      "Aceita financiamento",
      "Água",
      "Asfalto",
      "Muro",
      "Piso tátil"
    ],
    "description": "Apartamento à venda em Rita Vieira, Campo Grande MS, aceitando financiamento com churrasqueira, piscina, área de serviço, vaga coberta, interfone.",
    "images": [
      "assets/imoveis/imovel-0/foto-0.jpg",
      "assets/imoveis/imovel-0/foto-1.jpg",
      "assets/imoveis/imovel-0/foto-2.jpg",
      "assets/imoveis/imovel-0/foto-3.jpg",
      "assets/imoveis/imovel-0/foto-4.jpg",
      "assets/imoveis/imovel-0/foto-5.jpg",
      "assets/imoveis/imovel-0/foto-6.jpg",
      "assets/imoveis/imovel-0/foto-7.jpg",
      "assets/imoveis/imovel-0/foto-8.jpg",
      "assets/imoveis/imovel-0/foto-9.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "618158",
    "title": "Apartamento no Royal Park",
    "type": "Apartamento",
    "location": "Campo Grande - MS",
    "neighborhood": "Royal Park",
    "price": "R$ 1.400.000",
    "features": [
      "Área total: 257,00 m²",
      "Área construída: 142,00 m²",
      "Quartos: 3",
      "Banheiros: 4",
      "Vagas: 3",
      "Condomínio: R$ 1.000,00",
      "IPTU: R$ 7.600,00",
      "3 Suíte(s)",
      "1 Sala de estar",
      "1 Sala de jantar",
      "1 Sala de TV",
      "1 Sacada",
      "1 Wc social",
      "3 Vaga(s) de garagem",
      "Cozinha",
      "Campo de futebol",
      "Deck",
      "Hidromassagem",
      "Piscina infantil",
      "Salão de Jogos",
      "Academia",
      "Área de lazer",
      "Estacionamento para visitas",
      "Gazebo",
      "Portaria",
      "Quiosque",
      "Piso tátil",
      "Rampa de acessibilidade",
      "Automação predial",
      "Câmeras de segurança",
      "Piscina",
      "Calçada",
      "Sauna",
      "Salão de Festas",
      "Churrasqueira",
      "Recepção",
      "Jardim",
      "Interfone",
      "Porteiro eletrônico",
      "Quarto empregada",
      "Aceita financiamento",
      "Água",
      "Asfalto",
      "Muro",
      "Rede elétrica",
      "Esgoto",
      "Elevador"
    ],
    "description": "Apartamento novo à venda em Royal Park, Campo Grande MS, aceitando financiamento com 3 quartos, suíte, churrasqueira, piscina, cozinha, vaga coberta, elevador.",
    "images": [
      "assets/imoveis/imovel-1/foto-0.jpg",
      "assets/imoveis/imovel-1/foto-1.jpg",
      "assets/imoveis/imovel-1/foto-2.jpg",
      "assets/imoveis/imovel-1/foto-3.jpg",
      "assets/imoveis/imovel-1/foto-4.jpg",
      "assets/imoveis/imovel-1/foto-5.jpg",
      "assets/imoveis/imovel-1/foto-6.jpg",
      "assets/imoveis/imovel-1/foto-7.jpg",
      "assets/imoveis/imovel-1/foto-8.jpg",
      "assets/imoveis/imovel-1/foto-9.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "599677",
    "title": "Cobertura Duplex no Centro",
    "type": "Apto Cobertura Duplex",
    "location": "Campo Grande - MS",
    "neighborhood": "Centro",
    "price": "R$ 540.000",
    "features": [
      "Área total: 221,00 m²",
      "Área construída: 167,00 m²",
      "Quartos: 3",
      "Banheiros: 4",
      "Vaga: 1",
      "Condomínio: R$ 1.100,00",
      "IPTU: R$ 2.800,00",
      "1 Suíte(s) com a/e",
      "2 Quarto(s) com a/e",
      "2 Sala de estar",
      "1 Sala de jantar",
      "1 Sala de TV",
      "2 Wc social",
      "1 Vaga(s) de garagem",
      "Escritório",
      "Rede elétrica",
      "Esgoto",
      "Calçada",
      "Câmeras de segurança",
      "Academia",
      "Estacionamento para visitas",
      "Hall de entrada",
      "Portaria",
      "Terraço",
      "Aceita permuta",
      "Piso tátil",
      "WC adaptado",
      "Rampa de acessibilidade",
      "Automação predial",
      "Muro",
      "Asfalto",
      "Água",
      "Copa",
      "Cozinha",
      "Cozinha planejada",
      "Área de serviço",
      "Alarme",
      "Lavabo",
      "Churrasqueira",
      "Recepção",
      "Closet",
      "Despensa",
      "Porteiro eletrônico",
      "Quarto empregada",
      "Mezanino",
      "Aceita financiamento",
      "Elevador"
    ],
    "description": "Apto. Cobertura / Duplex à venda em Centro, Campo Grande MS, aceitando financiamento com 3 quartos, suíte, closet, churrasqueira, cozinha planejada, elevador.",
    "images": [
      "assets/imoveis/imovel-2/foto-0.jpg",
      "assets/imoveis/imovel-2/foto-1.jpg",
      "assets/imoveis/imovel-2/foto-2.jpg",
      "assets/imoveis/imovel-2/foto-3.jpg",
      "assets/imoveis/imovel-2/foto-4.jpg",
      "assets/imoveis/imovel-2/foto-5.jpg",
      "assets/imoveis/imovel-2/foto-6.jpg",
      "assets/imoveis/imovel-2/foto-7.jpg",
      "assets/imoveis/imovel-2/foto-8.jpg",
      "assets/imoveis/imovel-2/foto-9.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "552642",
    "title": "Casa Térrea - Bela Laguna",
    "type": "Casa Térrea",
    "location": "Campo Grande - MS",
    "neighborhood": "Bela Laguna",
    "price": "R$ 350.000",
    "features": [
      "Área total: 180,00 m²",
      "Área construída: 117,73 m²",
      "Quartos: 3",
      "Banheiros: 2",
      "Vagas: 2",
      "IPTU: R$ 1.000,00",
      "1 Suíte(s)",
      "2 Quarto(s)",
      "1 Sala de estar",
      "1 Sala de jantar",
      "1 Sala de TV",
      "1 Varanda",
      "1 Wc social",
      "2 Vaga(s) de garagem",
      "Cozinha",
      "Cozinha americana",
      "Calçada",
      "Esgoto",
      "Rede elétrica",
      "Muro",
      "Asfalto",
      "Água",
      "Aceita financiamento",
      "Portão elétrico",
      "Jardim",
      "Cerca elétrica",
      "Lavanderia",
      "Área de serviço",
      "Aceita permuta"
    ],
    "description": "Casa-Térrea à venda em Bela Laguna, Campo Grande MS, aceitando financiamento com 3 quartos, suíte, cozinha, área de serviço, vaga coberta, cerca elétrica.",
    "images": [
      "assets/imoveis/imovel-3/foto-0.jpg",
      "assets/imoveis/imovel-3/foto-1.jpg",
      "assets/imoveis/imovel-3/foto-2.jpg",
      "assets/imoveis/imovel-3/foto-3.jpg",
      "assets/imoveis/imovel-3/foto-4.jpg",
      "assets/imoveis/imovel-3/foto-5.jpg",
      "assets/imoveis/imovel-3/foto-6.jpg",
      "assets/imoveis/imovel-3/foto-7.jpg",
      "assets/imoveis/imovel-3/foto-8.jpg",
      "assets/imoveis/imovel-3/foto-9.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "657241",
    "title": "Casa Térrea - Santo Amaro",
    "type": "Casa Térrea",
    "location": "Campo Grande - MS",
    "neighborhood": "Santo Amaro",
    "price": "R$ 750.000",
    "features": [
      "Área total: 456,00 m²",
      "Área construída: 202,45 m²",
      "Quartos: 3",
      "Banheiro: 1",
      "Vagas: 5",
      "IPTU: R$ 150,00",
      "1 Suíte(s) com a/e",
      "2 Quarto(s) com a/e",
      "1 Sala de estar",
      "1 Sala de jantar",
      "1 Sala de TV",
      "5 Vaga(s) de garagem",
      "Cozinha",
      "Muro",
      "Esgoto",
      "Calçada",
      "Piscina",
      "Câmeras de segurança",
      "Poço artesiano",
      "Árvores frutíferas",
      "Depósito",
      "Asfalto",
      "Água",
      "Área de serviço",
      "Alarme",
      "Churrasqueira",
      "Jardim",
      "Interfone",
      "Edícula",
      "Portão elétrico",
      "Aceita financiamento",
      "Aceita permuta"
    ],
    "description": "Casa-Térrea à venda em Santo Amaro, Campo Grande MS, aceitando financiamento com 3 quartos, suíte, churrasqueira, piscina, cozinha, área de serviço.",
    "images": [
      "assets/imoveis/imovel-4/foto-0.jpg",
      "assets/imoveis/imovel-4/foto-1.jpg",
      "assets/imoveis/imovel-4/foto-2.jpg",
      "assets/imoveis/imovel-4/foto-3.jpg",
      "assets/imoveis/imovel-4/foto-4.jpg",
      "assets/imoveis/imovel-4/foto-5.jpg",
      "assets/imoveis/imovel-4/foto-6.jpg",
      "assets/imoveis/imovel-4/foto-7.jpg",
      "assets/imoveis/imovel-4/foto-8.jpg",
      "assets/imoveis/imovel-4/foto-9.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "649637",
    "title": "Casa Térrea - Solar dos Lagos",
    "type": "Casa em Condomínio",
    "location": "Bonito - MS",
    "neighborhood": "Solar dos Lagos",
    "price": "R$ 1.250.000",
    "features": [
      "Área total: 525,00 m²",
      "Área construída: 318,00 m²",
      "Quartos: 4",
      "Banheiros: 5",
      "Vagas: 2",
      "4 Suíte(s)",
      "1 Sala de estar",
      "1 Sala de TV",
      "1 Varanda",
      "1 Wc social",
      "2 Vaga(s) de garagem",
      "Copa",
      "Muro",
      "Rede elétrica",
      "Calçada",
      "Piscina",
      "Canil",
      "Cozinha americana",
      "Piscina infantil",
      "Hall de entrada",
      "Asfalto",
      "Água",
      "Cozinha",
      "Cozinha planejada",
      "Área de serviço",
      "Churrasqueira",
      "Lavanderia",
      "Despensa",
      "Porteiro eletrônico",
      "Portão elétrico",
      "Rampa de acessibilidade"
    ],
    "description": "Casa-Térrea-Condomínio à venda em Solar dos Lagos, Bonito MS com 4 quartos, suíte, churrasqueira, piscina, cozinha planejada, área de serviço.",
    "images": [
      "assets/imoveis/imovel-5/foto-0.jpg",
      "assets/imoveis/imovel-5/foto-1.jpg",
      "assets/imoveis/imovel-5/foto-2.jpg",
      "assets/imoveis/imovel-5/foto-3.jpg",
      "assets/imoveis/imovel-5/foto-4.jpg",
      "assets/imoveis/imovel-5/foto-5.jpg",
      "assets/imoveis/imovel-5/foto-6.jpg",
      "assets/imoveis/imovel-5/foto-7.jpg",
      "assets/imoveis/imovel-5/foto-8.jpg",
      "assets/imoveis/imovel-5/foto-9.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "665317",
    "title": "Terreno Altos da Afonso Pena (1)",
    "type": "Terreno em Condomínio",
    "location": "Campo Grande - MS",
    "neighborhood": "Altos da Afonso Pena",
    "price": "R$ 2.700.000",
    "features": [
      "Área total: 473,00 m²",
      "Área construída: 473,00 m²",
      "Condomínio: R$ 1.000,00",
      "IPTU: R$ 16.000,00",
      "Churrasqueira",
      "Câmeras de segurança",
      "Piscina infantil",
      "Salão de Jogos",
      "Quadra de areia",
      "Academia",
      "Área de lazer",
      "Estacionamento para visitas",
      "Portaria",
      "Energia solar fotovoltaica",
      "Calçada",
      "Esgoto",
      "Cerca elétrica",
      "Recepção",
      "Jardim",
      "Porteiro eletrônico",
      "Portão elétrico",
      "Água",
      "Asfalto",
      "Muro",
      "Rede elétrica",
      "Elevador"
    ],
    "description": "Terreno-Condomínio novo à venda em Altos da Afonso Pena, Campo Grande MS com churrasqueira, piscina, elevador, cerca elétrica, portão eletrônico.",
    "images": [
      "assets/imoveis/imovel-6/foto-0.jpg",
      "assets/imoveis/imovel-6/foto-1.jpg",
      "assets/imoveis/imovel-6/foto-2.jpg",
      "assets/imoveis/imovel-6/foto-3.jpg",
      "assets/imoveis/imovel-6/foto-4.jpg",
      "assets/imoveis/imovel-6/foto-5.jpg",
      "assets/imoveis/imovel-6/foto-6.jpg",
      "assets/imoveis/imovel-6/foto-7.jpg",
      "assets/imoveis/imovel-6/foto-8.jpg",
      "assets/imoveis/imovel-6/foto-9.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "689393",
    "title": "Terreno Altos da Afonso Pena (2)",
    "type": "Terreno em Condomínio",
    "location": "Campo Grande - MS",
    "neighborhood": "Altos da Afonso Pena",
    "price": "R$ 2.700.000",
    "features": [
      "Área total: 472,87 m²",
      "Condomínio: R$ 1.200,00",
      "IPTU: R$ 14.000,00",
      "Salão de Festas",
      "Salão de Jogos",
      "Quadra de areia",
      "Brinquedoteca",
      "Academia",
      "Área de lazer",
      "Estacionamento para visitas",
      "Gazebo",
      "Portaria",
      "Quiosque",
      "Cozinha Industrial",
      "Piso tátil",
      "Energia solar fotovoltaica",
      "Lago",
      "Câmeras de segurança",
      "Piscina",
      "Play-ground",
      "Guarita",
      "Cerca elétrica",
      "Recepção",
      "Jardim",
      "Porteiro eletrônico",
      "Portão elétrico",
      "Asfalto",
      "Muro",
      "Rede elétrica",
      "Esgoto",
      "Calçada",
      "Conveniência autônoma"
    ],
    "description": "Terreno-Condomínio novo à venda em Altos da Afonso Pena, Campo Grande MS com piscina, cerca elétrica, portão eletrônico. Agende sua visita!.",
    "images": [
      "assets/imoveis/imovel-7/foto-0.jpg",
      "assets/imoveis/imovel-7/foto-1.jpg",
      "assets/imoveis/imovel-7/foto-2.jpg",
      "assets/imoveis/imovel-7/foto-3.jpg",
      "assets/imoveis/imovel-7/foto-4.jpg",
      "assets/imoveis/imovel-7/foto-5.jpg",
      "assets/imoveis/imovel-7/foto-6.jpg",
      "assets/imoveis/imovel-7/foto-7.jpg",
      "assets/imoveis/imovel-7/foto-8.jpg",
      "assets/imoveis/imovel-7/foto-9.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "657381",
    "title": "Terreno Residencial Alphaville III",
    "type": "Terreno em Condomínio",
    "location": "Campo Grande - MS",
    "neighborhood": "Residencial Alphaville III",
    "price": "R$ 480.000",
    "features": [
      "Área total: 360,00 m²",
      "Salão de Festas",
      "Estacionamento para visitas",
      "Área de lazer",
      "Academia",
      "Quadra de areia",
      "Piscina infantil",
      "Câmeras de segurança",
      "Piscina",
      "Jardim",
      "Recepção",
      "Cerca elétrica",
      "Churrasqueira",
      "Play-ground",
      "Portaria"
    ],
    "description": "Terreno-Condomínio novo à venda em Residencial Alphaville III, Campo Grande MS com churrasqueira, piscina, cerca elétrica. Ótimo terreno - Alphaville III.",
    "images": [
      "assets/imoveis/imovel-8/foto-0.jpg",
      "assets/imoveis/imovel-8/foto-1.jpg",
      "assets/imoveis/imovel-8/foto-2.jpg",
      "assets/imoveis/imovel-8/foto-3.jpg",
      "assets/imoveis/imovel-8/foto-4.jpg",
      "assets/imoveis/imovel-8/foto-5.jpg",
      "assets/imoveis/imovel-8/foto-7.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "641633",
    "title": "Terreno Residencial Porto Royale",
    "type": "Terreno em Condomínio",
    "location": "Dourados - MS",
    "neighborhood": "Residencial Porto Royale",
    "price": "R$ 227.300",
    "features": [
      "Área total: 252,56 m²",
      "Salão de Festas",
      "Área de lazer",
      "Brinquedoteca",
      "Salão de Jogos",
      "Piscina infantil",
      "Piscina",
      "Calçada",
      "Esgoto",
      "Rede elétrica",
      "Asfalto",
      "Água",
      "Aceita financiamento",
      "Recepção",
      "Guarita",
      "Churrasqueira",
      "Play-ground",
      "Portaria"
    ],
    "description": "Terreno-Condomínio à venda em Residencial Porto Royale, Dourados MS, aceitando financiamento com churrasqueira, piscina. Agende sua visita!.",
    "images": [
      "assets/imoveis/imovel-9/foto-0.jpg",
      "assets/imoveis/imovel-9/foto-1.jpg",
      "assets/imoveis/imovel-9/foto-2.jpg",
      "assets/imoveis/imovel-9/foto-3.jpg",
      "assets/imoveis/imovel-9/foto-4.jpg",
      "assets/imoveis/imovel-9/foto-5.jpg",
      "assets/imoveis/imovel-9/foto-6.jpg",
      "assets/imoveis/imovel-9/foto-7.jpg",
      "assets/imoveis/imovel-9/foto-8.jpg",
      "assets/imoveis/imovel-9/foto-9.jpg"
    ],
    "proximidades": []
  },
  {
    "id": "697256",
    "title": "Apartamento mobiliado - 8º andar - Varandas Bella Vista",
    "type": "Apartamento",
    "location": "Campo Grande - MS",
    "neighborhood": "Itanhangá Park",
    "price": "R$ 775.000",
    "features": [
      "Área construída: 76,00 m²",
      "Quartos: 2",
      "Banheiros: 3",
      "Vaga: 1",
      "Endereço: R. Nova Era, 86 - torre 01 - 8º andar",
      "Mobiliado",
      "Condomínio Varandas Bella Vista",
      "Aceita financiamento",
      "Valor aproximado: R$ 10.197,37/m²",
      "Imóvel no 8º andar",
      "1 Suíte com armários",
      "1 Quarto com armários",
      "1 Sala de jantar",
      "1 Sala de TV",
      "1 Sacada gourmet",
      "1 Wc social",
      "Cozinha planejada",
      "Piscina",
      "Campo de futebol",
      "Piscina infantil",
      "Brinquedoteca",
      "Academia",
      "Área de lazer",
      "Estacionamento para visitas",
      "Hall de entrada",
      "Portaria",
      "Aceita permuta",
      "Elevador",
      "Salão de Festas",
      "Área de serviço",
      "Play-ground",
      "Lavabo",
      "Churrasqueira",
      "Lavanderia",
      "Recepção",
      "Jardim",
      "Interfone",
      "Closet",
      "Sacada com churrasqueira",
      "Rampa de acessibilidade",
      "Piso tátil",
      "Calçada",
      "Esgoto",
      "Rede elétrica",
      "Água",
      "Asfalto",
      "Muro"
    ],
    "description": "Apartamento mobiliado no 8º andar do Varandas Bella Vista, em Itanhangá Park, Campo Grande - MS. São 76 m², 2 quartos, 3 banheiros e 1 vaga de garagem.",
    "images": [
      "assets/imoveis/novos/apartamento-bella-vista-0.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-1.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-2.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-3.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-4.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-5.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-6.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-7.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-8.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-9.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-10.jpg",
      "assets/imoveis/novos/apartamento-bella-vista-11.jpg"
    ],
    "proximidades": [],
    "sourceUrl": "https://www.infoimoveis.com.br/imovel/venda-apartamento-ms-campo-grande-itanhanga-park/697256"
  },
  {
    "id": "697307",
    "title": "Sobrado com 3 quartos e suíte - 1 quadra da Lagoa",
    "type": "Sobrado",
    "location": "Campo Grande - MS",
    "neighborhood": "Jardim Itatiaia",
    "price": "R$ 520.000",
    "features": [
      "Área construída: 118,00 m²",
      "Quartos: 3",
      "Banheiros: 3",
      "Vaga: 1",
      "IPTU: R$ 1.600,00",
      "1 Suíte",
      "A 1 quadra da Lagoa",
      "Endereço: R. Ercy Cunha Martins",
      "Aceita financiamento",
      "Sobrado em condomínio",
      "Planta baixa disponível no anúncio",
      "1 Sala de jantar",
      "1 Sala de TV",
      "1 Sacada",
      "1 Varanda",
      "2 Wc social",
      "Cozinha",
      "Imóvel alugado com renda",
      "Caixa de água",
      "Calçada",
      "Esgoto",
      "Rede elétrica",
      "Muro",
      "Asfalto",
      "Água",
      "Portão elétrico",
      "Interfone",
      "Jardim",
      "Área de serviço",
      "Rampa de acessibilidade"
    ],
    "description": "Sobrado em condomínio no Jardim Itatiaia, a uma quadra da Lagoa, em Campo Grande - MS. Possui 118 m², 3 quartos sendo 1 suíte, 3 banheiros e 1 vaga de garagem.",
    "images": [
      "assets/imoveis/novos/sobrado-jardim-itatiaia.jpg"
    ],
    "proximidades": [
      "Padaria",
      "Farmácia",
      "Escola municipal",
      "Escola estadual",
      "Escola particular",
      "Praça",
      "Conveniência",
      "Mercado",
      "Posto de saúde",
      "Igreja",
      "Pista de caminhada"
    ],
    "sourceUrl": "https://www.infoimoveis.com.br/imovel/venda-sobrado-condominio-ms-campo-grande-jardim-itatiaia/697307"
  },
  {
    "id": "698182",
    "title": "Galpão - salão comercial reformado - mais de 1.000 m²",
    "type": "Imóvel Comercial",
    "purpose": "Aluguel",
    "location": "Campo Grande - MS",
    "neighborhood": "Monte Castelo",
    "price": "R$ 18.000/mês",
    "features": [
      "Área total: 1.200,00 m²",
      "Área construída: 1.000,00 m²",
      "Banheiros: 6",
      "Valor aluguel: R$ 18.000,00",
      "Salão comercial reformado",
      "Mais de 1.000 m²",
      "Endereço: Monte Castelo - Campo Grande - MS",
      "4 Wc social",
      "Escritório",
      "Galpão",
      "Caixa de água",
      "Estacionamento",
      "Pátio",
      "Sala de espera",
      "Vestiário",
      "Estacionamento para visitas",
      "Piso tátil",
      "WC adaptado",
      "Canil",
      "Calçada",
      "Esgoto",
      "WC de serviço",
      "Copa",
      "Lavabo",
      "Despensa",
      "Mezanino",
      "Água",
      "Asfalto",
      "Muro",
      "Rede elétrica",
      "Rampa de acessibilidade"
    ],
    "description": "Galpão e salão comercial reformado para aluguel no bairro Monte Castelo, em Campo Grande - MS, com 1.200 m² de área total, 1.000 m² de área construída e 6 banheiros.",
    "images": [
      "assets/imoveis/novos/galpao-monte-castelo.jpg"
    ],
    "proximidades": [],
    "sourceUrl": "https://www.infoimoveis.com.br/imovel/aluguel-imovel-comercial-ms-campo-grande-monte-castelo/698182"
  }
];
